name: Continuous Integration

# Trigger the workflow on pushes or pull requests to the main branch
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    # Run this job on an Ubuntu Linux runner
    runs-on: self-hosted

    steps:
    # Step 1: Check out the repository code onto the runner
    - name: Check out repository code
      uses: actions/checkout@v4

    # Step 2: Install Node.js on the runner environment
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # Step 3: Install dependencies and run tests
    - name: Install dependencies and test
      working-directory: source-code
      run: |
        npm ci
        npm test

  Sonarqube:
    name: Build and analyze
    runs-on: self-hosted
    needs: build-and-test

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      with:
        fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
    - uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v6.0.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  docker:
    runs-on: self-hosted
    name: Dockerizing the app
    needs: Sonarqube

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Build and push
      uses: docker/build-push-action@v7
      with:
        context: ./source-code
        file: ./source-code/Dockerfile
        push: true
        tags: silversoul007/dice-app:1.1
